version: '3.8'
services:
  social-backend:
    container_name: social-backend
    image: dergey/social-backend:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://social-mysql:3306/social?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_MAIL_HOST=social-mail
      - SPRING_MAIL_PORT=25
      - PRELOAD_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - "8080:8080"
  social-mysql:
    container_name: social-mysql
    image: mysql:8.0.28
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=social
    ports:
      - "127.0.0.1:3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  social-mail:
    container_name: social-mail
    image: ixdotai/smtp:latest
    environment:
      - RELAY_NETWORKS=:127.0.0.1/32 #, :192.168.31.0/24 # it only available in 192.168.31.0 network
      - MAILNAME=social.xpolr.space
    ports:
      - "127.0.0.1:25:25"