version: '3.8'
services:
  social-mail:
    container_name: social-mail
    image: ixdotai/smtp:latest
    platform: linux/x86_64
    environment:
      - RELAY_NETWORKS=:127.0.0.1/32 #, :192.168.31.0/24 # it only available in 192.168.31.0 network
      - MAILNAME=social.xpolr.space
    ports:
      - "127.0.0.1:25:25"